<?php

namespace AppBundle\Repository;

/**
 * HuchaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HuchaRepository extends \Doctrine\ORM\EntityRepository
{
}
