<?php

namespace AppBundle\Repository;

/**
 * TorpeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TorpeRepository extends \Doctrine\ORM\EntityRepository
{
}
